In [1]:
pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip



                                              0.0/16.5 MB ? eta -:--:--
                                              0.0/16.5 MB 1.3 MB/s eta 0:00:13
                                              0.1/16.5 MB 1.3 MB/s eta 0:00:13
                                              0.2/16.5 MB 1.5 MB/s eta 0:00:11
                                              0.4/16.5 MB 1.9 MB/s eta 0:00:09
     -                                        0.6/16.5 MB 2.6 MB/s eta 0:00:07
     -                                        0.8/16.5 MB 2.8 MB/s eta 0:00:06
     --                                       1.0/16.5 MB 3.2 MB/s eta 0:00:05
     ---                                      1.3/16.5 MB 3.6 MB/s eta 0:00:05
     ---                                      1.6/16.5 MB 3.8 MB/s eta 0:00:04
     ----                                     1.8/16.5 MB 3.9 MB/s eta 0:00:04
     -----                                    2.1/16.5 MB 4.2 MB/s eta 0:00:04
     -----                                    2.4/16.5 MB 

In [2]:
import numpy as np


In [3]:
data1D=np.array([1,2,3,4,5])


In [6]:
data2D=np.array([[1,2,3],[4,5,6]])

In [7]:
print(data1D.shape)

(5,)


In [8]:
print(data2D.shape)

(2, 3)


In [9]:
reshape_Arr=data2D.reshape(3,2)
print(reshape_Arr)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
print(data2D.ndim)

2


<!-- Array Indexing & Slicing -->


In [13]:
print(data1D[0])

1


In [15]:
print(data2D[1,2])

6


In [17]:
data2D

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# Slicing

print(data1D[:3])

[1 2 3]


In [18]:
print(data2D[:,1:])

[[2 3]
 [5 6]]
